# PyTorch Basics

In [2]:
!pip install torch

In [3]:
import torch as t
import numpy as np
t.manual_seed(811)

## Tensors

* A tensor is a container which can house data in N dimensions.

#### Creating Tensors

We can create tensors by specifying the shape as arguments.  Here is a tensor with 4 rows and 3 columns

In [11]:
a=t.Tensor(4, 3)
print("a is a ",type(a)) 

a

a is a  <class 'torch.Tensor'>


tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [7]:
b=t.randn(4, 3)
print("b is a ",type(b))
b

b is a  <class 'torch.Tensor'>


tensor([[-1.1484,  0.0960, -2.0328],
        [-0.0796, -0.7443,  0.3773],
        [ 0.1323, -0.5254, -0.7649],
        [-0.5431, -1.0292, -0.5761]])

Initialize tensors of ones or zeros.

In [10]:
#zeros
c=t.zeros(4,3)
c

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [12]:
#ones
c=t.ones(4,3)
c

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [13]:
#filling with numbers
c.fill_(9)

tensor([[9., 9., 9.],
        [9., 9., 9.],
        [9., 9., 9.],
        [9., 9., 9.]])

In [14]:
#diagonal fill
c.fill_diagonal_(3)

tensor([[3., 9., 9.],
        [9., 3., 9.],
        [9., 9., 3.],
        [9., 9., 9.]])

Tensors can be initialized and then filled in place. 

Note: operations that end in an underscore (`_`) are in place operations.

In [16]:
d = t.Tensor(2,2).fill_(2)
print(d.type())
print(d.shape)
print(d)

torch.FloatTensor
torch.Size([2, 2])
tensor([[2., 2.],
        [2., 2.]])


Tensors can be initialized from a list of lists

In [17]:
e=t.Tensor([[5, 6,],  
                  [1, 0,]])
e

tensor([[5., 6.],
        [1., 0.]])

Tensors can be initialized from numpy matrices

In [18]:
f = np.random.rand(3, 3)
f1=t.from_numpy(f)
print(f.dtype)
f1


float64


tensor([[0.7072, 0.8306, 0.2948],
        [0.9196, 0.8518, 0.5908],
        [0.3094, 0.9206, 0.5363]], dtype=torch.float64)

#### Tensor Types

The FloatTensor has been the default tensor that we have been creating all along

In [19]:
g = t.arange(6).view(2, 3)
g

tensor([[0, 1, 2],
        [3, 4, 5]])

In [21]:
x = t.FloatTensor([[1, 2, 3],  
                       [4, 5, 6]])
x


tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [22]:
x = x.long()
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [23]:
x = t.tensor([[1, 2, 3], 
                  [4, 5, 6]], dtype=t.int64)
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [24]:
x = x.float() 
x

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [25]:
x = t.randn(2, 3)
x

tensor([[ 0.1941,  0.1639, -0.4179],
        [-0.1050, -1.3437, -0.3375]])

In [26]:
(t.add(x, x))

tensor([[ 0.3883,  0.3278, -0.8357],
        [-0.2100, -2.6874, -0.6750]])

In [27]:
(x + x)

tensor([[ 0.3883,  0.3278, -0.8357],
        [-0.2100, -2.6874, -0.6750]])

In [28]:
h = t.arange(6)
h

tensor([0, 1, 2, 3, 4, 5])

In [34]:
h1=h.view(2, 3)
h1

tensor([[0, 1, 2],
        [3, 4, 5]])

In [35]:
(t.sum(h1, dim=0))


tensor([3, 5, 7])

In [36]:
(t.sum(h1, dim=1))

tensor([ 3, 12])

In [37]:
(t.transpose(h1, 0, 1))

tensor([[0, 3],
        [1, 4],
        [2, 5]])

In [43]:
x = t.arange(6).view(2, 3)
x

tensor([[0, 1, 2],
        [3, 4, 5]])

In [44]:
(x[:1, :2])

tensor([[0, 1]])

In [41]:
(x[0, 1])

tensor(1)

In [21]:
indices = t.LongTensor([0, 2])
describe(torch.index_select(x, dim=1, index=indices))

Type: torch.LongTensor
Shape/size: torch.Size([2, 2])
Values: 
tensor([[0, 2],
        [3, 5]])


In [46]:
indices = t.LongTensor([0, 0])
(t.index_select(x, dim=0, index=indices))

tensor([[0, 1, 2],
        [0, 1, 2]])

In [23]:
row_indices = torch.arange(2).long()
col_indices = torch.LongTensor([0, 1])
describe(x[row_indices, col_indices])

Type: torch.LongTensor
Shape/size: torch.Size([2])
Values: 
tensor([0, 4])


Long Tensors are used for indexing operations and mirror the `int64` numpy type

In [48]:
x = t.LongTensor([[1, 2, 3],  
                      [4, 5, 6],
                      [7, 8, 9]])

print(x.dtype)
print(x.numpy().dtype)

torch.int64
int64


You can convert a FloatTensor to a LongTensor

In [50]:
x = t.FloatTensor([[1, 2, 3],  
                       [4, 5, 6],
                       [7, 8, 9]])
x = x.long()
x

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

### Special Tensor initializations

We can create a vector of incremental numbers

In [51]:
x = t.arange(0, 10)
print(x)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


Sometimes it's useful to have an integer-based arange for indexing

In [52]:
x = t.arange(0, 10).long()
print(x)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


## Operations

Using the tensors to do linear algebra is a foundation of modern Deep Learning practices

Reshaping allows you to move the numbers in a tensor around.  One can be sure that the order is preserved.  In PyTorch, reshaping is called `view`

In [53]:
x = t.arange(0, 20)

print(x.view(1, 20))
print(x.view(2, 10))
print(x.view(4, 5))
print(x.view(5, 4))
print(x.view(10, 2))
print(x.view(20, 1))

tensor([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
         18, 19]])
tensor([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])
tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]])
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])
tensor([[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]])
tensor([[ 0],
        [ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10],
        [11],
        [12],
        [13],
        [14],
        [15],
        [16],
        [17],
        [18],
        [19]])


We can use view to add size-1 dimensions, which can be useful for combining with other tensors.  This is called broadcasting. 

In [54]:
x = t.arange(12).view(3, 4)
y = t.arange(4).view(1, 4)
z = t.arange(3).view(3, 1)

print(x)
print(y)
print(z)
print(x + y)
print(x + z)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
tensor([[0, 1, 2, 3]])
tensor([[0],
        [1],
        [2]])
tensor([[ 0,  2,  4,  6],
        [ 4,  6,  8, 10],
        [ 8, 10, 12, 14]])
tensor([[ 0,  1,  2,  3],
        [ 5,  6,  7,  8],
        [10, 11, 12, 13]])


Unsqueeze and squeeze will add and remove 1-dimensions.

In [57]:
x = t.arange(12).view(3, 4)
print(x.shape)

x = x.unsqueeze(dim=1)
print(x.shape)
print(x)
x = x.squeeze()
print(x.shape)
print(x)

torch.Size([3, 4])
torch.Size([3, 1, 4])
tensor([[[ 0,  1,  2,  3]],

        [[ 4,  5,  6,  7]],

        [[ 8,  9, 10, 11]]])
torch.Size([3, 4])
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])


all of the standard mathematics operations apply (such as `add` below)

In [60]:
x = t.rand(3,4)
y = t.rand(3,4)
print("x: \n", x)
print("--")
print("t.add(x, y): \n", t.add(x, y))
print("--")
print("x+y: \n", x + y)

x: 
 tensor([[0.7147, 0.7214, 0.4703, 0.9002],
        [0.7762, 0.8589, 0.0524, 0.6233],
        [0.6608, 0.7636, 0.8773, 0.6750]])
--
t.add(x, y): 
 tensor([[1.1223, 1.2752, 0.5069, 1.3083],
        [0.9596, 0.9810, 0.2973, 0.7191],
        [0.7520, 1.0757, 1.4545, 1.2532]])
--
x+y: 
 tensor([[1.1223, 1.2752, 0.5069, 1.3083],
        [0.9596, 0.9810, 0.2973, 0.7191],
        [0.7520, 1.0757, 1.4545, 1.2532]])


The convention of `_` indicating in-place operations continues:

In [61]:
x = t.arange(12).reshape(3, 4)
print(x)
print(x.add_(x))

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
tensor([[ 0,  2,  4,  6],
        [ 8, 10, 12, 14],
        [16, 18, 20, 22]])


There are many operations for which reduce a dimension.  Such as sum:

In [66]:
x = t.arange(8).reshape(2, 4)
print("x: \n", x)
print("---")
print("Summing across rows (dim=0): \n", x.sum(dim=0))
print("---")
print("Summing across columns (dim=1): \n", x.sum(dim=1))

x: 
 tensor([[0, 1, 2, 3],
        [4, 5, 6, 7]])
---
Summing across rows (dim=0): 
 tensor([ 4,  6,  8, 10])
---
Summing across columns (dim=1): 
 tensor([ 6, 22])


#### Indexing, Slicing, Joining and Mutating

In [68]:
x = t.arange(6).view(2, 3)
print("x: \n", x)
print("---")
print("x[:2, :2]: \n", x[:2, :2])
print("---")
print("x[0][1]: \n", x[0][1])
print("---")
print("Setting [0][1] to be 8")
x[0][1] = 97
print(x)

x: 
 tensor([[0, 1, 2],
        [3, 4, 5]])
---
x[:2, :2]: 
 tensor([[0, 1],
        [3, 4]])
---
x[0][1]: 
 tensor(1)
---
Setting [0][1] to be 8
tensor([[ 0, 97,  2],
        [ 3,  4,  5]])


We can select a subset of a tensor using the `index_select`

In [70]:
x = t.arange(9).view(3,3)
print(x)

print("---")
indices = t.LongTensor([0, 2])
print(t.index_select(x, dim=0, index=indices))

print("---")
indices = t.LongTensor([0, 2])
print(t.index_select(x, dim=1, index=indices))

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])
---
tensor([[0, 1, 2],
        [6, 7, 8]])
---
tensor([[0, 2],
        [3, 5],
        [6, 8]])


We can also use numpy-style advanced indexing:

In [71]:
x = t.arange(9).view(3,3)
indices = t.LongTensor([0, 2])

print(x[indices])
print("---")
print(x[indices, :])
print("---")
print(x[:, indices])

tensor([[0, 1, 2],
        [6, 7, 8]])
---
tensor([[0, 1, 2],
        [6, 7, 8]])
---
tensor([[0, 2],
        [3, 5],
        [6, 8]])


We can combine tensors by concatenating them.  First, concatenating on the rows

In [72]:
x = t.arange(6).view(2,3)
print(t.cat([x, x], dim=0))
print(t.cat([x, x], dim=1))
print(t.stack([x, x]))

tensor([[0, 1, 2],
        [3, 4, 5],
        [0, 1, 2],
        [3, 4, 5]])
tensor([[0, 1, 2, 0, 1, 2],
        [3, 4, 5, 3, 4, 5]])
tensor([[[0, 1, 2],
         [3, 4, 5]],

        [[0, 1, 2],
         [3, 4, 5]]])


We can concentate along the first dimension.. the columns.

In [73]:
x = t.arange(9).view(3,3)

print(x)
print("---")
new_x = t.cat([x, x, x], dim=1)
print(new_x.shape)
print(new_x)

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])
---
torch.Size([3, 9])
tensor([[0, 1, 2, 0, 1, 2, 0, 1, 2],
        [3, 4, 5, 3, 4, 5, 3, 4, 5],
        [6, 7, 8, 6, 7, 8, 6, 7, 8]])


We can also concatenate on a new 0th dimension to "stack" the tensors:

In [74]:
x = t.arange(9).view(3,3)
print(x)
print("---")
new_x = t.stack([x, x, x])
print(new_x.shape)
print(new_x)

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])
---
torch.Size([3, 3, 3])
tensor([[[0, 1, 2],
         [3, 4, 5],
         [6, 7, 8]],

        [[0, 1, 2],
         [3, 4, 5],
         [6, 7, 8]],

        [[0, 1, 2],
         [3, 4, 5],
         [6, 7, 8]]])


#### Linear Algebra Tensor Functions

Transposing allows you to switch the dimensions to be on different axis. So we can make it so all the rows are columsn and vice versa. 

In [75]:
x = t.arange(0, 12).view(3,4)
print("x: \n", x) 
print("---")
print("x.tranpose(1, 0): \n", x.transpose(1, 0))

x: 
 tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
---
x.tranpose(1, 0): 
 tensor([[ 0,  4,  8],
        [ 1,  5,  9],
        [ 2,  6, 10],
        [ 3,  7, 11]])


A three dimensional tensor would represent a batch of sequences, where each sequence item has a feature vector.  It is common to switch the batch and sequence dimensions so that we can more easily index the sequence in a sequence model. 

Note: Transpose will only let you swap 2 axes.  Permute (in the next cell) allows for multiple

In [76]:
batch_size = 3
seq_size = 4
feature_size = 5

x = t.arange(batch_size * seq_size * feature_size).view(batch_size, seq_size, feature_size)

print("x.shape: \n", x.shape)
print("x: \n", x)
print("-----")

print("x.transpose(1, 0).shape: \n", x.transpose(1, 0).shape)
print("x.transpose(1, 0): \n", x.transpose(1, 0))

x.shape: 
 torch.Size([3, 4, 5])
x: 
 tensor([[[ 0,  1,  2,  3,  4],
         [ 5,  6,  7,  8,  9],
         [10, 11, 12, 13, 14],
         [15, 16, 17, 18, 19]],

        [[20, 21, 22, 23, 24],
         [25, 26, 27, 28, 29],
         [30, 31, 32, 33, 34],
         [35, 36, 37, 38, 39]],

        [[40, 41, 42, 43, 44],
         [45, 46, 47, 48, 49],
         [50, 51, 52, 53, 54],
         [55, 56, 57, 58, 59]]])
-----
x.transpose(1, 0).shape: 
 torch.Size([4, 3, 5])
x.transpose(1, 0): 
 tensor([[[ 0,  1,  2,  3,  4],
         [20, 21, 22, 23, 24],
         [40, 41, 42, 43, 44]],

        [[ 5,  6,  7,  8,  9],
         [25, 26, 27, 28, 29],
         [45, 46, 47, 48, 49]],

        [[10, 11, 12, 13, 14],
         [30, 31, 32, 33, 34],
         [50, 51, 52, 53, 54]],

        [[15, 16, 17, 18, 19],
         [35, 36, 37, 38, 39],
         [55, 56, 57, 58, 59]]])


Permute is a more general version of tranpose:

In [78]:
batch_size = 3
seq_size = 4
feature_size = 5

x = t.arange(batch_size * seq_size * feature_size).view(batch_size, seq_size, feature_size)

print("x.shape: \n", x.shape)
print("x: \n", x)
print("-----")

print("x.permute(1, 0, 2).shape: \n", x.permute(1, 0, 2).shape)
print("x.permute(1, 0, 2): \n", x.permute(1, 0, 2))

x.shape: 
 torch.Size([3, 4, 5])
x: 
 tensor([[[ 0,  1,  2,  3,  4],
         [ 5,  6,  7,  8,  9],
         [10, 11, 12, 13, 14],
         [15, 16, 17, 18, 19]],

        [[20, 21, 22, 23, 24],
         [25, 26, 27, 28, 29],
         [30, 31, 32, 33, 34],
         [35, 36, 37, 38, 39]],

        [[40, 41, 42, 43, 44],
         [45, 46, 47, 48, 49],
         [50, 51, 52, 53, 54],
         [55, 56, 57, 58, 59]]])
-----
x.permute(1, 0, 2).shape: 
 torch.Size([4, 3, 5])
x.permute(1, 0, 2): 
 tensor([[[ 0,  1,  2,  3,  4],
         [20, 21, 22, 23, 24],
         [40, 41, 42, 43, 44]],

        [[ 5,  6,  7,  8,  9],
         [25, 26, 27, 28, 29],
         [45, 46, 47, 48, 49]],

        [[10, 11, 12, 13, 14],
         [30, 31, 32, 33, 34],
         [50, 51, 52, 53, 54]],

        [[15, 16, 17, 18, 19],
         [35, 36, 37, 38, 39],
         [55, 56, 57, 58, 59]]])


Matrix multiplication is `mm`:

In [81]:
t.randn(2, 3, requires_grad=True)

tensor([[ 1.7716,  0.2756, -0.1288],
        [ 0.2675,  0.0427,  0.4815]], requires_grad=True)

In [82]:
x1 = t.arange(6).view(2, 3).float()
print(x1)

x2 = t.ones(3, 2)
x2[:, 1] += 1
print(x2)

print(t.mm(x1, x2))

tensor([[0., 1., 2.],
        [3., 4., 5.]])
tensor([[1., 2.],
        [1., 2.],
        [1., 2.]])
tensor([[ 3.,  6.],
        [12., 24.]])


Check the [PyTorch Math Operations Documentation](https://pytorch.org/docs/stable/torch.html#math-operations) for more!

## Computing Gradients

In [83]:
x = t.tensor([[2.0, 3.0]], requires_grad=True)
z = 3 * x
print(z)

tensor([[6., 9.]], grad_fn=<MulBackward0>)


In this small snippet, you can see the gradient computations at work.  We create a tensor and multiply it by 3.  Then, we create a scalar output using `sum()`.  A Scalar output is needed as the the loss variable. Then, called backward on the loss means it computes its rate of change with respect to the inputs.  Since the scalar was created with sum, each position in z and x are independent with respect to the loss scalar. 

The rate of change of x with respect to the output is just the constant 3 that we multiplied x by.

In [87]:
x = t.tensor([[7.0, 9.0]], requires_grad=True)
print("x: \n", x)
print("---")
z = 3 * x
print("z = 3*x: \n", z)
print("---")

loss = z.sum()
print("loss = z.sum(): \n", loss)
print("---")

loss.backward()

print("after loss.backward(), x.grad: \n", x.grad)


x: 
 tensor([[7., 9.]], requires_grad=True)
---
z = 3*x: 
 tensor([[21., 27.]], grad_fn=<MulBackward0>)
---
loss = z.sum(): 
 tensor(48., grad_fn=<SumBackward0>)
---
after loss.backward(), x.grad: 
 tensor([[3., 3.]])


### Example: Computing a conditional gradient

$$ \text{ Find the gradient of f(x) at x=1 } $$
$$ {} $$
$$ f(x)=\left\{
\begin{array}{ll}
    sin(x) \text{ if } x>0 \\
    cos(x) \text{ otherwise } \\
\end{array}
\right.$$

In [89]:
def f(x):
    if (x.data > 0).all():
        return t.sin(x)
    else:
        return t.cos(x)

In [94]:
x = t.tensor([3.0], requires_grad=True)
y = f(x)
print(x)
y.backward()
print(x.grad)

tensor([3.], requires_grad=True)
tensor([-0.9900])


We could apply this to a larger vector too, but we need to make sure the output is a scalar:

Making the output a scalar:

In [96]:
x = t.tensor([1.0, 0.5], requires_grad=True)
y = f(x)
y.sum().backward()
print(x.grad)

tensor([0.5403, 0.8776])


but there was an issue.. this isn't right for this edge case:

In [97]:
x = t.tensor([1.0, -1], requires_grad=True)
y = f(x)
y.sum().backward()
print(x.grad)

tensor([-0.8415,  0.8415])


In [98]:
x = t.tensor([-0.5, -1], requires_grad=True)
y = f(x)
y.sum().backward()
print(x.grad)

tensor([0.4794, 0.8415])


### CUDA Tensors

PyTorch's operations can seamlessly be used on the GPU or on the CPU.  There are a couple basic operations for interacting in this way.

In [39]:
print(t.cuda.is_available())

False


In [85]:
device = t.device("cuda" if t.cuda.is_available() else "cpu")
print(device)

cpu
